In [18]:
#引入pandas, 因为Series,DataFrame使用较多，所以直接引进
#这两个是Pandas的主要数据结构
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

In [4]:
#Series
obj = pd.Series([4,3,2,111,43])
obj

0      4
1      3
2      2
3    111
4     43
dtype: int64

In [5]:
obj.values

array([  4,   3,   2, 111,  43])

In [6]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
obj2 = pd.Series([4,7,5,14], index=['e','r','k','l'])

In [8]:
obj2

e     4
r     7
k     5
l    14
dtype: int64

In [9]:
obj2.values

array([ 4,  7,  5, 14])

In [10]:
obj2.index

Index(['e', 'r', 'k', 'l'], dtype='object')

In [12]:
obj2['e']

4

In [13]:
obj2[['e','k']]

e    4
k    5
dtype: int64

In [15]:
obj2[obj2>5]

r     7
l    14
dtype: int64

In [16]:
obj2*2

e     8
r    14
k    10
l    28
dtype: int64

In [19]:
np.exp(obj2)

e    5.459815e+01
r    1.096633e+03
k    1.484132e+02
l    1.202604e+06
dtype: float64

In [20]:
'e' in obj2

True

In [21]:
't' in obj2

False

In [22]:
data = {'OIjh' : 1123, 'TReef' : 1123213, 'AZ' : 2232}

In [23]:
obj3 = pd.Series(data)
obj3

OIjh        1123
TReef    1123213
AZ          2232
dtype: int64

In [25]:
indd = ['AS', 'AZ', 'TReef','OIjh','hh']
obj4 = pd.Series(data,index=indd)
obj4

AS             NaN
AZ          2232.0
TReef    1123213.0
OIjh        1123.0
hh             NaN
dtype: float64

In [26]:
pd.isnull(obj4)

AS        True
AZ       False
TReef    False
OIjh     False
hh        True
dtype: bool

In [27]:
pd.notnull(obj4)

AS       False
AZ        True
TReef     True
OIjh      True
hh       False
dtype: bool

In [28]:
obj.isnull()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [29]:
obj4.isnull()

AS        True
AZ       False
TReef    False
OIjh     False
hh        True
dtype: bool

In [32]:
obj4.name = 'useless'
obj4.index.name = 'uuusse'

In [33]:
obj4

uuusse
AS             NaN
AZ          2232.0
TReef    1123213.0
OIjh        1123.0
hh             NaN
Name: useless, dtype: float64

In [36]:
obj4.index=['hah','lal','xx','luelue','ee']

In [37]:
obj4

hah             NaN
lal          2232.0
xx        1123213.0
luelue       1123.0
ee              NaN
Name: useless, dtype: float64

In [39]:
#DataFrame
data = {
   'state' : ['liaoning','liaoning','jilin','jilin','heilongj','dalian'],
    'year' : [2000,2001,2003,2000,2001,2005],
    'revenue':[2300,2500,2900,2000,2500,2900]
}
frame = pd.DataFrame(data)

In [40]:
frame

state  year  revenue
0  liaoning  2000     2300
1  liaoning  2001     2500
2     jilin  2003     2900
3     jilin  2000     2000
4  heilongj  2001     2500
5    dalian  2005     2900

In [42]:
frame.head()

state  year  revenue
0  liaoning  2000     2300
1  liaoning  2001     2500
2     jilin  2003     2900
3     jilin  2000     2000
4  heilongj  2001     2500

In [44]:
pd.DataFrame(data,columns=['year','state','revenue'])

year     state  revenue
0  2000  liaoning     2300
1  2001  liaoning     2500
2  2003     jilin     2900
3  2000     jilin     2000
4  2001  heilongj     2500
5  2005    dalian     2900

In [48]:
frame2=pd.DataFrame(data,columns=['year','state','revenue','happy'],index=['one','two','three','four','five','six'])

In [49]:
frame2

year     state  revenue happy
one    2000  liaoning     2300   NaN
two    2001  liaoning     2500   NaN
three  2003     jilin     2900   NaN
four   2000     jilin     2000   NaN
five   2001  heilongj     2500   NaN
six    2005    dalian     2900   NaN

In [50]:
frame2.columns

Index(['year', 'state', 'revenue', 'happy'], dtype='object')

In [51]:
frame2['state']

one      liaoning
two      liaoning
three       jilin
four        jilin
five     heilongj
six        dalian
Name: state, dtype: object

In [53]:
frame2.loc['three']

year        2003
state      jilin
revenue     2900
happy        NaN
Name: three, dtype: object

In [55]:
frame2['happy'] = np.arange(6)

In [56]:
frame2

year     state  revenue  happy
one    2000  liaoning     2300      0
two    2001  liaoning     2500      1
three  2003     jilin     2900      2
four   2000     jilin     2000      3
five   2001  heilongj     2500      4
six    2005    dalian     2900      5

In [57]:
val = pd.Series([-1.2,4.5,33], index=['three','four','one'])
frame2['happy'] = val
frame2

year     state  revenue  happy
one    2000  liaoning     2300   33.0
two    2001  liaoning     2500    NaN
three  2003     jilin     2900   -1.2
four   2000     jilin     2000    4.5
five   2001  heilongj     2500    NaN
six    2005    dalian     2900    NaN

In [58]:
frame2['estt'] = frame2.state == 'liaoning'
frame2

year     state  revenue  happy   estt
one    2000  liaoning     2300   33.0   True
two    2001  liaoning     2500    NaN   True
three  2003     jilin     2900   -1.2  False
four   2000     jilin     2000    4.5  False
five   2001  heilongj     2500    NaN  False
six    2005    dalian     2900    NaN  False

In [59]:
del frame2['estt']

In [60]:
frame2

year     state  revenue  happy
one    2000  liaoning     2300   33.0
two    2001  liaoning     2500    NaN
three  2003     jilin     2900   -1.2
four   2000     jilin     2000    4.5
five   2001  heilongj     2500    NaN
six    2005    dalian     2900    NaN

In [64]:
pop = {'Xian' : {2001:5000, 2002:9000,2003:4500,2006:10500},
        'chengdu' : {2001:7000,2002:9500, 2003:10500}
      }
frame3 = pd.DataFrame(pop)
frame3

Xian  chengdu
2001   5000   7000.0
2002   9000   9500.0
2003   4500  10500.0
2006  10500      NaN

In [65]:
frame3.T

2001    2002     2003     2006
Xian     5000.0  9000.0   4500.0  10500.0
chengdu  7000.0  9500.0  10500.0      NaN

In [67]:
frame3.index.name = 'year'
frame3.columns.name = 'province'

In [68]:
frame3

province   Xian  chengdu
year                    
2001       5000   7000.0
2002       9000   9500.0
2003       4500  10500.0
2006      10500      NaN

In [69]:
frame3.values

array([[ 5000.,  7000.],
       [ 9000.,  9500.],
       [ 4500., 10500.],
       [10500.,    nan]])

In [70]:
frame2.values

array([[2000, 'liaoning', 2300, 33.0],
       [2001, 'liaoning', 2500, nan],
       [2003, 'jilin', 2900, -1.2],
       [2000, 'jilin', 2000, 4.5],
       [2001, 'heilongj', 2500, nan],
       [2005, 'dalian', 2900, nan]], dtype=object)